# Generated by Django 4.2 on 2023-04-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowing_service", "0004_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")], max_length=8
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "Payment"), ("Fine", "Fine")], max_length=7
                    ),
                ),
                ("session_url", models.URLField(max_length=255)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing_service.borrowing",
                    ),
                ),
            ],
            options={
                "ordering": ["money_to_pay"],
            },
        ),
    ]
